In [1]:
import yfinance as yf
import pandas as pd

In [2]:
df_1 = pd.read_csv('S000006408.csv')

In [5]:
df_1.head()

,Unnamed: 0,CIK,Tickers,Stock,20231231,20230930,20230630,20230331,20221231,20220930,...,20211231,20210930,20210630,20210331,20201231,20200930,20200630,20200331,20191231,20190930
0,0,12659,HRB,H&R Block Inc,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.128197,0.162650,0.190063,0.209042
1,1,27419,TGT,Target Corp,0.000000,0.000000,0.000000,0.000000,2.255422,2.334395,...,2.704304,2.893718,3.089763,2.691495,2.626773,3.264594,2.796957,2.787354,2.693603,2.394350
2,2,29534,DG,Dollar General Corp,0.000000,0.000000,0.000000,0.000000,1.826384,1.847288,...,1.312940,1.281167,1.318384,1.346709,1.530945,2.162499,2.236707,2.274791,1.646417,1.790276
3,3,39911,GPS,Gap Inc/The,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.090205,0.124924,0.176724,0.166206,0.123416,0.144957,0.125308,0.088627,0.155966,0.163958
4,4,46080,HAS,Hasbro Inc,0.177538,0.283185,0.263889,0.214964,0.260452,0.296912,...,0.312766,0.295247,0.308193,0.333114,0.354221,0.436655,0.445432,0.538693,0.557168,0.614234

In [ ]:
# Define your list of tickers
tickers = data['Ticker']

# Define the start and end date for your desired period
start_date = "2023-12-31"  # Adjust this as needed
end_date = "2024-03-31"  # Today's date by default

# Create an empty DataFrame to store the data
summary_data_df = pd.DataFrame(columns=["Ticker", "Date", "Open", "Close"])

In [ ]:
summary_data_df.head()

In [ ]:
# Loop through each ticker in the list
for ticker in tickers:
  # Download historical data for the current ticker
  try:
    df = yf.download(ticker, start=start_date, end=end_date)
  except (yf.DownloadError, ValueError) as e:
    print(f"Error downloading data for {ticker}: {e}")
    continue  # Skip to the next ticker if download fails

  # Extract relevant data and create a temporary DataFrame
  temp_df = pd.DataFrame({"Ticker": ticker, "Date": df.index, "Open": df["Open"], "Close": df["Close"]})

  # Append the temporary DataFrame to the main DataFrame
  summary_data_df = pd.concat([summary_data_df, temp_df], ignore_index=True)